services:
  transparencia-bot:
    build: .
    container_name: transparencia_bot
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    tty: true
